#访问端口
server:
  port: 8085

spring:
    #******************************************视图配置*****************************************
    thymeleaf:
      #开启模板缓存（默认值：true）
      cache: false
      #Check that the template exists before rendering it.
      check-template: true
      #检查模板位置是否正确(默认值:true)
      check-template-location: true
      servlet:
        #Content-Type的值（默认值：text/html）
        content-type: text/html
      #开启MVC Thymeleaf视图解析(默认值：true)
      enabled: true
      #模板编码
      encoding: utf-8
      #要被排除在解析之外的视图名称列表，用逗号分隔
      excluded-view-names:
      #要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
      mode: HTML5
      #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
      prefix: classpath:/templates/
      #在构建URL时添加到视图名称后的后缀（默认值：.html）
      suffix: .html
#******************************************日志配置*****************************************
#logging:
# config: classpath:logback-spring.xml
# path: F:/log








